version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/auth-teste
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=adm
    depends_on:
      - db
  
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=auth-teste
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=adm
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: